name: Generate package-lock.json

on:
  workflow_dispatch:
  push:
    paths:
      - package.json

permissions:
  contents: write

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'   # matches Vercel
          cache: 'npm'

      - name: Install deps (create lockfile)
        run: npm install

      - name: Commit lockfile if changed
        run: |
          if [[ -n "$(git status --porcelain package-lock.json)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add package-lock.json
            git commit -m "chore: add/update package-lock.json (auto)"
            git push
          else
            echo "No changes to package-lock.json"
          fi
